name: Esse3
description: Esse3 Unimore

version: 1.4.2+43

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.15
  html: ^0.15.0
  add_2_calendar: ^2.1.3
  url_launcher: ^6.1.4
  fl_chart: ^0.55.0
  liquid_pull_to_refresh: ^3.0.1
  flutter_svg: ^1.1.0
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPro-Regular.otf
        - asset: assets/fonts/SFPro-Light.otf
          weight: 300
        - asset: assets/fonts/SFPro-Thin.otf
          weight: 100
        - asset: assets/fonts/SFPro-Medium.otf
          weight: 500
        - asset: assets/fonts/SFPro-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFPro-Bold.otf
          weight: 700