name: Esse3
description: Esse3 Unimore

version: 1.3.0+36


environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  shared_preferences: ^2.0.3
  sqflite: ^2.0.0+2
  path: ^1.8.0
  path_provider: ^2.0.1
  html: ^0.15.0
  add_2_calendar: ^1.4.0
  url_launcher: ^6.0.2
  fl_chart: ^0.20.1
  liquid_pull_to_refresh: ^2.0.0
  flutter_svg: 0.21.0-nullsafety.0
  shimmer: ^1.1.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPro-Regular.otf
        - asset: assets/fonts/SFPro-Light.otf
          weight: 300
        - asset: assets/fonts/SFPro-Thin.otf
          weight: 100
        - asset: assets/fonts/SFPro-Medium.otf
          weight: 500
        - asset: assets/fonts/SFPro-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFPro-Bold.otf
          weight: 700