name: Esse3
description: Esse3 Unimore

version: 1.2.0+26

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.0
  path: ^1.6.4
  path_provider: ^1.6.7
  html: ^0.14.0+4
  add_2_calendar: ^1.4.0
  url_launcher: ^5.7.10
  fl_chart: ^0.12.0
  liquid_pull_to_refresh: ^2.0.0
  flutter_svg: ^0.19.1
  shimmer: ^1.1.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFPro-Regular.otf
        - asset: assets/fonts/SFPro-Light.otf
          weight: 300
        - asset: assets/fonts/SFPro-Thin.otf
          weight: 100
        - asset: assets/fonts/SFPro-Medium.otf
          weight: 500
        - asset: assets/fonts/SFPro-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFPro-Bold.otf
          weight: 700